### ISSUE TITLE
TensorFlow update

### ISSUE THREAD

**Issue by archenroot** [camaclean/bw-python-gentoo-prefix-overlay#1]
Hi, I tried your TensorFlow ebuild, but failed on:
 no such package '@bazel_tools//tools/cpp': error loading package 'external': Could not load //external package

Do you plan any updated version of this package?

Regards,

Ladislav

**Comment by archenroot** [comment]
Sorry mistake, this issue I have with another TensorFlow ebuild available at:
https://github.com/zougloub/gentoo-zougloub-overlay/blob/03da97eaa2df141b571ee0a0ff74b0a3f2cc94c4/sci-libs/tensorflow/tensorflow-0.6.0.ebuild

**Comment by archenroot** [comment]
Unfortunatelly, your ebuild also doesn't work for me, do you plan also update to at least 0.11 version or provide 9999 ebuild. 

Thank you very much.

**Comment by camaclean** [comment]
These ebuilds are not intended for general usage. They are created for use with Gentoo Prefix hosted on Cray Linux Environment and may also (inadvertently) have site-specific configurations only relevant for use on the Blue Waters supercomputer.

**Comment by archenroot** [comment]
Aha :-) I see. Are you aware of some general usage TensorFlow ebuild available, zugaina didn't help a lot. Otherwise I try the one refered above. This was the only second ebuild I found available.
